services:
  dev-db:
    image: postgres:latest
    container_name: nest_postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
  test-db:
    image: postgres:latest
    container_name: test_nest_postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_test